version: "3.8"

services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: shortenerdb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/varl/lib/postgresql.data

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        ports:
            - "4000:4000"
        environment:
            DATABASE_URL: postgres://postgres:password@db:5432/shortenerdb
            PORT: 4000

volumes:
    pgdata:
